query GetChannelCountries {
  activeChannel {
    defaultShippingZone {
      id
      name
      members {
        id
        code
        name
      }
    }
  }
}

query GetChannelTheme {
  activeChannel {
    customFields {
      themeId
      shopContent
      detailConfig
    }
  }
}
