# Queries
query GetActiveCustomer {
  activeCustomer {
    ...CustomerBase
  }
}

query GetActiveCustomerDetail {
  activeCustomer {
    ...CustomerDetail
  }
}

query GetCustomerAddresses {
  activeCustomer {
    id
    addresses {
      id
      fullName
      defaultShippingAddress
      streetLine1
      streetLine2
      city
      province
      postalCode
      country {
        code
        name
      }
      phoneNumber
    }
  }
}

# Mutations
mutation LogInUser(
  $emailAddress: String!
  $password: String!
  $rememberMe: Boolean!
) {
  login(username: $emailAddress, password: $password, rememberMe: $rememberMe) {
    ... on CurrentUser {
      ...CurrentUser
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation LogOutUser {
  logout {
    success
  }
}

mutation RegisterCustomerAccount($input: RegisterCustomerInput!) {
  registerCustomerAccount(input: $input) {
    ... on Success {
      success
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation VerifyCustomerAccount($password: String, $token: String!) {
  verifyCustomerAccount(password: $password, token: $token) {
    ... on CurrentUser {
      ...CurrentUser
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation RequestPasswordReset($emailAddress: String!) {
  requestPasswordReset(emailAddress: $emailAddress) {
    ... on Success {
      success
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation ResetPassword($token: String!, $password: String!) {
  resetPassword(token: $token, password: $password) {
    ... on CurrentUser {
      ...CurrentUser
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation CreateCustomerAddress($input: CreateAddressInput!) {
  createCustomerAddress(input: $input) {
    id
  }
}

mutation UpdateCustomerAddress($input: UpdateAddressInput!) {
  updateCustomerAddress(input: $input) {
    id
  }
}

mutation DeleteCustomerAddress($id: ID!) {
  deleteCustomerAddress(id: $id) {
    success
  }
}
