# Queries
query GetActiveOrder {
  activeOrder {
    ...OrderBase
  }
}

query GetActiveOrderDetail {
  activeOrder {
    ...OrderDetail
  }
}

query GetShippingMethods {
  eligibleShippingMethods {
    id
    price
    name
    code
    description
  }
}

query GetPaymentMethods {
  eligiblePaymentMethods {
    id
    name
    code
    isEligible
  }
}

query GetOrderByCode($code: String!) {
  orderByCode(code: $code) {
    ...OrderDetail
  }
}

query GetOrderHistory($options: OrderListOptions) {
  activeCustomer {
    orders(options: $options) {
      totalItems
      items {
        ...OrderBase
        orderPlacedAt
      }
    }
  }
}

# Mutations
mutation AddItemToOrder($variantId: ID!, $quantity: Int!) {
  addItemToOrder(productVariantId: $variantId, quantity: $quantity) {
    __typename
    ...OrderBase
    ... on ErrorResult {
      errorCode
      message
    }
    ... on InsufficientStockError {
      quantityAvailable
      order {
        ...OrderBase
      }
    }
  }
}

mutation RemoveItemFromOrder($orderLineId: ID!) {
  removeOrderLine(orderLineId: $orderLineId) {
    __typename
    ...OrderBase
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation AdjustOrderLine($orderLineId: ID!, $quantity: Int!) {
  adjustOrderLine(orderLineId: $orderLineId, quantity: $quantity) {
    __typename
    ...OrderBase
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation ApplyCouponCode($couponCode: String!) {
  applyCouponCode(couponCode: $couponCode) {
    __typename
    ...OrderBase
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation RemoveCouponCode($couponCode: String!) {
  removeCouponCode(couponCode: $couponCode) {
    __typename
    ...OrderBase
  }
}

mutation SetCustomerForOrder($input: CreateCustomerInput!) {
  setCustomerForOrder(input: $input) {
    __typename
    ...OrderDetail
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation SetOrderShippingAddress($input: CreateAddressInput!) {
  setOrderShippingAddress(input: $input) {
    __typename
    ...OrderDetail
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation SetShippingMethod($id: [ID!]!) {
  setOrderShippingMethod(shippingMethodId: $id) {
    __typename
    ...OrderDetail
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation TransitionToState($state: String!) {
  transitionOrderToState(state: $state) {
    __typename
    ...OrderDetail
    ... on OrderStateTransitionError {
      errorCode
      message
      transitionError
      fromState
      toState
    }
  }
}

mutation AddPaymentToOrder($input: PaymentInput!) {
  addPaymentToOrder(input: $input) {
    __typename
    ...OrderDetail
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

mutation SetOrderCustomFields($input: UpdateOrderInput!) {
  setOrderCustomFields(input: $input) {
    __typename
    ...OrderDetail
    ... on ErrorResult {
      errorCode
      message
    }
  }
}

# ===== 按配送档案分箱 + 支付拆合（后端 cjk-plugin）=====

query GetOrderBoxes {
  orderBoxes {
    boxKey
    profileId
    profileName
    lineIds
    tenantChannelId
    shippingProfileIds
    availableShippingMethodIds
    defaultShippingMethodId
    requiresAddress
    requiresContact
    availablePaymentMethodCodes
    pickupLocations {
      id
      name
      type
      address
      phoneNumber
      businessHours
      coordinates
    }
  }
}

mutation SetOrderBoxShippingMethod($boxKey: String!, $shippingMethodId: ID!, $pickupLocationId: ID) {
  setOrderBoxShippingMethod(
    boxKey: $boxKey
    shippingMethodId: $shippingMethodId
    pickupLocationId: $pickupLocationId
  ) {
    __typename
    ...OrderDetail
  }
}

mutation CheckoutSplitted($method: String!, $metadata: String) {
  checkoutSplitted(method: $method, metadata: $metadata) {
    __typename
    ...OrderDetail
  }
}
