query GetProduct($id: ID!) {
  product(id: $id) {
    ...ProductBaseFragment
  }
}

query GetProductDetail($slug: String!) {
  product(slug: $slug) {
    ...ProductDetailFragment
  }
}

query GetProductVariantStock($productId: ID!, $variantId: String!) {
  product(id: $productId) {
    variantList(options: { filter: { id: { eq: $variantId } } }) {
      items {
        stockLevel
      }
    }
  }
}

query GetProducts($take: Int = 12, $skip: Int = 0) {
  products(options: { take: $take, skip: $skip }) {
    items {
      ...ProductBaseFragment
    }
    totalItems
  }
}

query SearchProducts(
  $term: String!
  $skip: Int
  $take: Int
  $collectionSlug: String
) {
  search(
    input: {
      term: $term
      groupByProduct: true
      skip: $skip
      take: $take
      collectionSlug: $collectionSlug
    }
  ) {
    totalItems
    items {
      ...ProductSearchFragment
    }
  }
}

query GetProductsByIds($ids: [String!]) {
  products(options: { filter: { id: { in: $ids } } }) {
    items {
      ...ProductBaseFragment
    }
  }
}
