fragment OrderBase on Order {
  id
  code
  couponCodes
  state
  totalQuantity
  totalWithTax
  currencyCode
  customer {
    id
    firstName
    lastName
    emailAddress
  }
  lines {
    id
    unitPriceWithTax
    quantity
    linePriceWithTax
    productVariant {
      id
      name
    }
    featuredAsset {
      id
      preview
    }
  }
  customFields {
    lat
    lng
    city
    deliveryType
  }
}

fragment OrderDetail on Order {
  id
  code
  couponCodes
  state
  currencyCode
  totalQuantity
  subTotal
  shippingWithTax
  totalWithTax
  orderPlacedAt
  customer {
    id
    firstName
    lastName
    emailAddress
  }
  shippingAddress {
    fullName
    streetLine1
    streetLine2
    city
    postalCode
    country
  }
  billingAddress {
    fullName
    streetLine1
    streetLine2
    city
    postalCode
    country
  }
  discounts {
    description
    amountWithTax
  }
  lines {
    id
    unitPriceWithTax
    quantity
    linePriceWithTax
    proratedLinePrice
    productVariant {
      id
      name
      sku
    }
    featuredAsset {
      id
      preview
    }
  }
  payments {
    method
  }
  shippingLines {
    shippingMethod {
      name
    }
  }
  taxSummary {
    description
    taxTotal
  }
  fulfillments {
    id
    state
    method
  }
  customFields {
    lat
    lng
    city
    deliveryType
    selectedPickupLocationId {
      id
      name
      type
      address
      phoneNumber
      businessHours
    }
    pickupType
    pickupClaimed
    packageShippingJson
    shippingAdjustment
  }
}
