fragment ProductVariantFragment on ProductVariant {
  id
  name
  sku
  stockLevel
  availableStock
  currencyCode
  price
  priceWithTax
  options {
    id
    name
    group {
      id
      name
    }
  }
  featuredAsset {
    id
    preview
  }
  assets {
    id
    preview
  }
  customFields {
    videoUrl
  }
}

fragment ProductBaseFragment on Product {
  id
  name
  slug
  description
  featuredAsset {
    id
    preview
  }
  variants {
    currencyCode
    price
  }
  customFields {
    belongCity
    serviceCities
    displayTemplate
    videoUrl
  }
}

fragment ProductDetailFragment on Product {
  ...ProductBaseFragment
  assets {
    id
    preview
  }
  collections {
    id
    name
    slug
    parent {
      id
      name
      slug
    }
  }
  variants {
    ...ProductVariantFragment
  }
}

fragment ProductSearchFragment on SearchResult {
  productId
  productName
  slug
  productAsset {
    id
    preview
  }
  priceWithTax {
    ... on SinglePrice {
      value
    }
    ... on PriceRange {
      min
      max
    }
  }
  currencyCode
}
