from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    ctx = browser.new_context(viewport={"width": 1440, "height": 900}, locale="zh-CN")
    page = ctx.new_page()
    page.on("console", lambda m: print(f"[console.{m.type}] {m.text}"))
    page.goto("https://www.youshop.cn/product/bluetooth-earbuds-pro", timeout=60000)
    page.wait_for_load_state("networkidle")
    page.get_by_role("button", name="立即购买").first.click()
    page.wait_for_timeout(2500)
    page.get_by_role("button", name="新增地址").first.click()
    page.wait_for_timeout(1000)
    page.fill("input[name=fullName]", "张三")
    page.fill("input[name=phoneNumber]", "13800138000")
    section = page.locator("section[aria-labelledby=address-block-heading]")
    section.locator("button.group.rounded-md").nth(1).click()
    page.wait_for_timeout(2500)
    page.screenshot(path="shots/16_province_fixed.png", full_page=False)
    t = page.locator("body").inner_text()
    i = t.find("省份")
    print("=== after province click ===")
    print(t[i:i+700])
    # 尝试选第一个省（北京市/北京市），驱动后续级联
    items = page.locator("[role=option], li", has_text="北京市").all()
    print("province option count:", len(items))
    browser.close()